[tox]
envlist = py3
isolated_build = true

[testenv]
package = editable
extras = dev,bulma
commands =
    pip install -e {toxinidir}/djcrud-mcp
    pytest -m "not splinter and not drf" -n auto {posargs}
    pytest -m splinter -n 0 --splinter-headless {posargs}

[testenv:drf]
package = editable
extras = dev,bulma,drf,mcp
commands =
    pip install -e {toxinidir}/djcrud-mcp
    pytest -m drf -n 0 {posargs}
passenv =
    DISPLAY
    MOZ_HEADLESS
    GITHUB_*