"""
Test URL consistency between urlpatterns generation and view.url property.

This ensures that view.url can correctly reverse the URLs created by urlpatterns.
Also tests that Django templates don't swallow exceptions from view properties.
"""

import pytest
from django.urls import reverse, clear_url_caches
from django.test import override_settings, Client
from django.template import Template, Context

from djcrud.mvc import Controller, View
from djcrud.views.template import TemplateView


@pytest.mark.django_db
class TestURLConsistency:
    """Test that view.url matches the URLs generated by urlpatterns."""

    def test_nested_controller_url_consistency(self):
        """View.url should correctly reverse nested controller URLs."""
        # Create a three-level hierarchy: Root > Auth > User
        class UserListView(TemplateView):
            urlpath = ''
            urlname = 'list'
            template_name = 'test.html'
            has_perm = True

        class UserController(Controller):
            urlpath = 'user'
            views = [UserListView]

        class AuthController(Controller):
            urlpath = 'auth'
            views = [UserController]

        root = Controller(views=[AuthController])

        # Get the URLconf patterns
        urlpatterns = root.urlpatterns

        # Temporarily set up URL routing
        with override_settings(ROOT_URLCONF=__name__):
            # Set module-level urlpatterns for Django's URL resolver
            globals()['urlpatterns'] = urlpatterns
            clear_url_caches()

            # Get a view instance from the hierarchy
            auth_controller = root.views[0]
            user_controller = auth_controller.views[0]
            user_list_view = user_controller.views[0]

            # Create an instance of the view
            view_instance = user_list_view()

            # The view should be able to compute its URL
            computed_url = view_instance.url

            # The URL should be reversible and match what we expect
            # Expected namespace: auth:user:list
            expected_url = reverse('auth:user:list')

            assert computed_url == expected_url
            assert computed_url == '/auth/user/'

    def test_single_controller_url_consistency(self):
        """View.url should work with single-level controller."""
        class ListView(TemplateView):
            urlpath = ''
            urlname = 'list'
            template_name = 'test.html'
            has_perm = True

        class UserController(Controller):
            urlpath = 'user'
            views = [ListView]

        root = Controller(views=[UserController])
        urlpatterns = root.urlpatterns

        with override_settings(ROOT_URLCONF=__name__):
            globals()['urlpatterns'] = urlpatterns
            clear_url_caches()

            user_controller = root.views[0]
            list_view = user_controller.views[0]
            view_instance = list_view()

            computed_url = view_instance.url
            expected_url = reverse('user:list')

            assert computed_url == expected_url
            assert computed_url == '/user/'

    def test_root_view_url_consistency(self):
        """View.url should work for views directly in root controller."""
        class HomeView(TemplateView):
            urlpath = ''
            urlname = 'home'
            template_name = 'test.html'
            has_perm = True

        root = Controller(views=[HomeView])
        urlpatterns = root.urlpatterns

        with override_settings(ROOT_URLCONF=__name__):
            globals()['urlpatterns'] = urlpatterns
            clear_url_caches()

            home_view = root.views[0]
            view_instance = home_view()

            computed_url = view_instance.url
            expected_url = reverse('home')

            assert computed_url == expected_url
            assert computed_url == '/'

    def test_view_with_path_params_url(self):
        """View.url should raise NoReverseMatch for views with path parameters when called without args."""
        from django.urls.exceptions import NoReverseMatch

        class DetailView(TemplateView):
            urlpath = '<int:pk>/'
            urlname = 'detail'
            template_name = 'test.html'
            has_perm = True

        class UserController(Controller):
            urlpath = 'user'
            views = [DetailView]

        root = Controller(views=[UserController])
        urlpatterns = root.urlpatterns

        with override_settings(ROOT_URLCONF=__name__):
            globals()['urlpatterns'] = urlpatterns
            clear_url_caches()

            user_controller = root.views[0]
            detail_view = user_controller.views[0]
            view_instance = detail_view()

            # Should raise NoReverseMatch because we don't have required parameters
            with pytest.raises(NoReverseMatch):
                _ = view_instance.url


@pytest.mark.django_db
class TestTemplateExceptionPropagation:
    """Test that Django templates don't swallow exceptions from view properties."""

    def test_template_raises_exception_from_view_property(self):
        """Template rendering should propagate exceptions from view properties."""
        from django.urls.exceptions import NoReverseMatch

        # Create a view that will raise an exception when accessing .url
        class DetailView(TemplateView):
            urlpath = '<int:pk>/'
            urlname = 'detail'
            template_name = 'test.html'
            has_perm = True

        class UserController(Controller):
            urlpath = 'user'
            views = [DetailView]

        root = Controller(views=[UserController])
        urlpatterns = root.urlpatterns

        with override_settings(ROOT_URLCONF=__name__):
            globals()['urlpatterns'] = urlpatterns
            clear_url_caches()

            detail_view = root.views[0].views[0]
            view_instance = detail_view()

            # Try to render a template that accesses view.url
            template = Template("{{ view.url }}")
            context = Context({'view': view_instance})

            # Should raise NoReverseMatch, not return empty string
            with pytest.raises(NoReverseMatch):
                template.render(context)

    def test_template_renders_valid_url_property(self):
        """Template should successfully render valid view.url."""
        class ListView(TemplateView):
            urlpath = ''
            urlname = 'list'
            template_name = 'test.html'
            has_perm = True

        class UserController(Controller):
            urlpath = 'user'
            views = [ListView]

        root = Controller(views=[UserController])
        urlpatterns = root.urlpatterns

        with override_settings(ROOT_URLCONF=__name__):
            globals()['urlpatterns'] = urlpatterns
            clear_url_caches()

            list_view = root.views[0].views[0]
            view_instance = list_view()

            # Render template with view.url
            template = Template("{{ view.url }}")
            context = Context({'view': view_instance})
            rendered = template.render(context)

            # Should render the actual URL
            assert rendered == '/user/'

    def test_template_raises_exception_from_view_title(self):
        """Template should propagate exceptions from view.title when model is None."""
        from djcrud.views import ListView

        # ListView without a model will fail when title is accessed
        class BrokenListView(ListView):
            urlpath = ''
            urlname = 'list'

        broken_view = BrokenListView()
        broken_view.request = None

        # Title tries to access self.model._meta which will fail
        template = Template("{{ view.title }}")
        context = Context({'view': broken_view})

        # Should raise AttributeError, not return empty string
        with pytest.raises(AttributeError, match="'NoneType' object has no attribute '_meta'"):
            template.render(context)
