# Generated by Django 6.0.6 on 2026-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_example', '0002_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
