# Generated by Django 6.0.6 on 2026-07-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action_example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Story",
        ),
    ]
