"""
Django settings for djcrud_example project.

Uses os.getenv('DJCRUD_FRONTEND', 'djcrud_bulma') to include only the selected frontend in INSTALLED_APPS.
No special middleware or context processors are required — mvc.View.get_context_data injects `view` and `site_controller`.
"""
import os

# Generated by 'django-admin startproject' using Django 5.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/








from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$)lvizx#(3&go_%&a%!&bi!q9dtc#a9p5@61#mr!t0@(cm^z6k"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_tables2",
    "crispy_forms",
    "crispy_bootstrap5",  # for djcrud_bootstrap (optional if using bulma only)
    "crispy_bulma",  # required for "bulma" template pack (per crispy-bulma docs; provides templates)
    "djcrud",
    os.getenv("DJCRUD_FRONTEND", "djcrud_bulma"),
    "djcrud_auth",
]

# Frontend selected via DJCRUD_FRONTEND env var (default djcrud_bulma). Only the selected
# frontend is in INSTALLED_APPS. Its AppConfig.ready() auto-sets DJCRUD_FRONTEND,
# CRISPY_TEMPLATE_PACK, DJCRUD_TABLES2_*, CRISPY_ALLOWED_TEMPLATE_PACKS.
# crispy-bulma package provides all templates for "bulma" pack (no local overrides/duplication).
# Supports `pip install djcrud[bulma]` or `djcrud[bootstrap]`.
# See djcrud_bulma/apps.py and djcrud_bootstrap/apps.py for details.

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djcrud_example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # No djcrud.context_processors needed: mvc.View.get_context_data injects `view` + `site_controller=root_controller`
            ],
        },
    },
]

WSGI_APPLICATION = "djcrud_example.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
