"""
Django settings for djcrud_example project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hi*x0s1^_s)@j*w=9-oeea^swlw#$=k3ud*si4&z79k2ae43*a"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "dal",
    "dal_alight",
    "queryset_sequence",
    "dal_queryset_sequence",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # core
    "djcrud",
    "djcrud_dal",
    "djcrud_dal_topbar",
    # load the auth router in djcrud.site:
    "djcrud_auth",
    # audit log: patches ModelRouter + registers LogEntryRouter
    "djcrud_history",
    # secure trigger hook registry
    "djcrud_triggers",
    # routing introspection for superusers at /debug/router/ and /debug/url/
    "djcrud_debug",
    # Token model for djcrud_drf login routes (see docs/tutorial/drf.rst)
    "djcrud_api",
    "rest_framework",
    "drf_spectacular",
    "djcrud_drf",
    "djcrud_mcp",
    # template pack
    "djcrud_bulma",
    # used by djcrud_bulma:
    "crispy_forms",
    "crispy_bulma",
    "django_tables2",
    # tutorial example apps (see docs/tutorial/)
    "djcrud_example.routing_example",
    "djcrud_example.security_example",
    "djcrud_example.views_example",
    "djcrud_example.action_example",
    "djcrud_example.listaction_example",
    "djcrud_example.search_example",
    "djcrud_example.drf_example",
    "djcrud_example.mcp_example",
    "djcrud_example.spa_example",
    # load a custom user model
    "djcrud_example",
]

AUTH_USER_MODEL = "djcrud_example.User"

LOGIN_URL = "/auth/login/"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Bearer token middleware — enable per docs/tutorial/drf.rst:
    # "djcrud_api.middleware.BearerCsrfMiddleware",  # before CsrfViewMiddleware
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "djcrud_api.middleware.BearerUserMiddleware",  # after AuthenticationMiddleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djcrud_example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.template.context_processors.csrf",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "string_if_invalid": "⚠️ UNDEFINED: %s ⚠️",
        },
    },
]

WSGI_APPLICATION = "djcrud_example.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(os.path.dirname(__file__)) / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ("en", "English"),
    ("fr", "French"),
    ("de", "German"),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
